### ISSUE TITLE
boot into previous version automatically if the current one fails to boot

### ISSUE THREAD

**Issue by mihaelaapetroaie** [advancedtelematic/meta-updater#350]
Hello,

I am trying to build OSTree on a raspberry pi using yocto (rocko branch) and your layers and I was wondering if there is any way to make my system boot into the previous version automatically if the latest update broke the OS and does not allow it to boot. I would prefer if this could be done automatically, in case my device is deployed somewhere where I do not have physical access to it.

Thank you for your help.

**Comment by OYTIS** [comment]
@mihaelaapetroaie 
Rollback on Raspberry Pi should be enabled by default on Rocko (please shout if it doesn't work for you). It will be ported to newer branches (sumo and master) soon.

**Comment by patrickvacek** [comment]
@mihaelaapetroaie It has since been merged into master, and a PR for sumo is pending. Is there anything else we can help you with, or can we close this issue?

**Comment by patrickvacek** [comment]
Closing due to lack of response and existing solution to the problem.
