### ISSUE TITLE
Barebox AS Bootloader

### ISSUE THREAD

**Issue by doganmurat** [advancedtelematic/meta-updater#43]
Hi,

You have u-boot examples for Raspberry Pi etc..
Do you have any example or some documentation for barebox?
Thanks.

**Comment by OYTIS** [comment]
Hi @doganmurat,

currently we support only u-boot and have some rudimentary support for Grub. We are of course willing to add support for as many bootloaders as possible. To add support for barebox we first need to add respective integration code to [ostree](https://github.com/ostreedev/ostree) (see e.g. [u-boot module](https://github.com/ostreedev/ostree/blob/master/src/libostree/ostree-bootloader-uboot.c)), so it may take a while. Any help is gratefully accepted.

Thanks
