### ISSUE TITLE
Support for updating fpga bitstream

### ISSUE THREAD

**Issue by Bubu** [advancedtelematic/meta-updater#482]
For our board (based on xilinx zynq) we need to load an fpga bitstream from u-boot before starting Linux.

Ideally this should just be handled alongside kernel and initrmfs which can be updated via ostree. But I couldn't find an obvious way to expand this to other files.

(Together with the bitstream the devivetree needs to be updated)

How should we go about solving this?

**Comment by ricardosalveti** [comment]
Can the fpga bitstream be loaded as part of the fitimage (kernel+initrd+fpga)?

**Comment by Bubu** [comment]
Good idea, I think we had this originally before switching to meta-updater layer.
Is fit image support something new here, I remember it not being supported...:thinking:.

**Comment by OYTIS** [comment]
@Bubu FIT images have been added last March and have been greatly improved in August. It is mostly used/tested for Raspberry Pi, so you might want to take a look at `meta-updater-raspberrypi` layer as well.

**Comment by Bubu** [comment]
Thanks, I'll take a look at fit images again. One question for clarification:

This would mean we'd put the bitstream and dtb file both into the fit image, right? And I guess we can also put an additional uboot script for updating the boot commands in there?

**Comment by OYTIS** [comment]
> This would mean we'd put the bitstream and dtb file both into the fit image, right?

Yes, that's how FIT images work. We've never used this feature of U-Boot, but the code seems to be there. Just make sure that all relevant CONFIG_* options are enabled.

> And I guess we can also put an additional uboot script for updating the boot commands in there?

Actually you can, there is a dedicated image type in FIT for that ('script') and u-boot seems to know how to use it (with `source` command). Integrating that with Yocto/OE is a different story, I couldn't find any support for that in oe-core.

**Comment by patrickvacek** [comment]
Closing due to lack of feedback.
