### ISSUE TITLE
Recent commit breaking compatibility with thud and warrior

### ISSUE THREAD

**Issue by albard00** [advancedtelematic/meta-updater#555]
Hi there,
I just discovered a small issue that appeared recently:

https://github.com/advancedtelematic/meta-updater/commit/12dbe3116ed539767ca5d283dd558b565e864a2c is breaking the compatibility with warrior and thud because openssl_1.1.1c.bb does not exist. The openssl version in thud and warrior is 1.1.1b. 1.1.1c is only present in master

Thanks for your work

Best regards

**Comment by lbonn** [comment]
Hello and thanks for the report.

We currently don't recommend using the master branch of meta-updater with other yocto release branches as we backport changes that make sense to the corresponding meta-updater branches.

You can use our thud branch, but we indeed don't have a warrior branch at the moment, that's on our list.

**Comment by patrickvacek** [comment]
@albard00 Yes, it's probably time for a warrior branch. Until that commit, master was more-or-less compatible with warrior, but that unfortunately isn't true anymore. Thanks for letting us know!

**Comment by lbonn** [comment]
I've proposed to upstream the patch to openembedded. If accepted, we will be able to drop it here.

**Comment by lbonn** [comment]
Reference: https://patchwork.openembedded.org/patch/163219/. When merged it will actually break our master because of the duplicate patch :). Then we'll just drop it and this issue will be solved.

**Comment by lbonn** [comment]
Fixed by #559
