### ISSUE TITLE
Outdated OSTree branch reference in SRC_URI of ostree_git.bb files 

### ISSUE THREAD

**Issue by stephaneberle9** [advancedtelematic/meta-updater#817]
Affected branches (non-exhaustive): **rocko**, **warrior**

Current `SCR_URI` value in `recipes-sota\ostree\ostree_git.bb` file: 

```
SRC_URI = "gitsm://github.com/ostreedev/ostree.git;branch=master"
```

Actual branches in `https://github.com/ostreedev/ostree`: 

![image](https://user-images.githubusercontent.com/1942528/128562092-41594643-bd4d-44e6-8d2b-e7700cd1e1d4.png)

Change to fix the issue:

```
SRC_URI = "gitsm://github.com/ostreedev/ostree.git;branch=main"
```

**Comment by pattivacek** [comment]
Thanks for the warning. IIRC rocko is not a supported branch anymore and AFAIK no one is using the warrior branch. I updated thud for my own needs; feel free to send PRs for the other two branches if you'd like.

By the way, do you have a script for detecting this sort of branch rename? :)

**Comment by stephaneberle9** [comment]
>  feel free to send PRs for the other two branches if you'd like.

Done for `rocko`, `warrior`, `krogoth`, `sumo`, `pyro `and `morty`

> By the way, do you have a script for detecting this sort of branch rename? :)

No, I stumbled upon this issue because I've a rocko-based upstream project that was no longer compiling, and then just pocked around manually to find other branches with the same inconsistency ;)

**Comment by pattivacek** [comment]
That's dedication! Thanks.
